title: Enter Code to Pair Spotify
description: <a href="https://spotifypaircodes.com/"><img src="/aks.png"alt="spotify.com/pair"/></a>
theme:  jekyll-theme-cayman
bing_site_verification: <meta name="msvalidate.01" content="1998AC068791C33D5177641F5A481522" />
